name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: actuated
    steps:
      - uses: actions/checkout@master
        with:
          repository: alexellis/arkade
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - name: Make all
        run: go test -race ./...
